using UnityEngine;
using System.Collections;
using System.ComponentModel;


public enum ClavierEnum
{
    [Description("Rose(_)")]
    Rose,
    [Description("Paquerette(_)")]
    Paquerette,
    [Description("Tulipe(_)")]
    Tulipe,
    [Description("est_grand(_)")]
    est_grand,
    [Description("est_moyen(_)")]
    est_moyen,
    [Description("est_petit(_)")]
    est_petit,
    [Description("est_rouge(_)")]
    est_rouge,
    [Description("est_rose(_)")]
    est_rose,
    [Description("est_blanc(_)")]
    est_blanc,
    [Description("a_l_est(_)")]
    a_l_est,
    [Description("a_l_ouest(_)")]
    a_l_ouest,
    [Description("au_sud(_)")]
    au_sud,
    [Description("au_nord(_)")]
    au_nord,
    [Description("a_l_est_de(_,_)")]
    a_l_est_de,
    [Description("au_sud_de(_,_)")]
    au_sud_de,
    [Description("au_nord_de(_,_)")]
    au_nord_de,
    [Description("meme_latitude(_,_)")]
    meme_latitude,
    [Description("meme_longitude(_,_)")]
    meme_longitude,
    [Description("plus_grand_que(_,_)")]
    plus_grand_que,
    [Description("plus_petit_que(_,_)")]
    plus_petit_que,
    [Description("meme_taille_que(_,_)")]
    meme_taille_que,
    [Description("meme_couleur_que(_,_)")]
    meme_couleur_que,
    [Description("egal(_,_)")]
    egal,
    [Description("est_entre(_,_,_)")]
    est_entre,
    F1_Atom,
    [Description("¬")]
    F1_Neg,
     [Description("∧")]
    F1_And,
     [Description("∨")]
    F1_Or,
      [Description("⇒")]
    F1_Impl,
    [Description("∀")]
    F1_Forall,
    [Description("∃")]
    F1_Exists,
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    v,
    w,
    x,
    y,
    z
}
 